export { default as aiGirl1 } from './ai-girl1.png';
export { default as aiGirl2 } from './ai-girl2.png';
export { default as aiJacket } from './ai-jacket.png';
export { default as market1 } from './market1.png';
export { default as market2 } from './market2.png';
export { default as figNosComun1 } from './list-nossa-comunidade1.png';
export { default as figNosComun2 } from './list-nossa-comunidade2.png';
export { default as figNosComun3 } from './list-nossa-comunidade3.png';
export { default as figNosComun4 } from './list-nossa-comunidade4.png';
export { default as figNosComun5 } from './list-nossa-comunidade5.png';
export { default as figParEmpr1 } from './list-para-empresas1.png';
export { default as figParEmpr2 } from './list-para-empresas2.png';
export { default as figParEmpr3 } from './list-para-empresas3.png';
export { default as figParEmpr4 } from './list-para-empresas4.png';
export { default as figParEmpr5 } from './list-para-empresas5.png';
export { default as heitorFt } from './heitor-ft-edited.png'
export { default as mateusFt } from './mateus-ft-edited.jpeg'
export { default as lucianoFt } from './luciano-ft-edited.jpeg'
